jr_photo:
    resource: "@jrPhotoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
    pattern: /login
    defaults: { _controller:jrPhotoBundle:Security:login }

login_check:
    pattern:  /login_check

logout:
    pattern:  /logout


