# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        jr\PhotoBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user:
            entity: { class: jrPhotoBundle:User, property: pseudo }

    firewalls:
        photo_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /
    access_control:
            - { path: ^/user, roles: ROLE_ADMIN }
            - { path: ^/menu, roles: ROLE_ADMIN }
            - { path: ^/photo, roles: ROLE_ADMIN }


