jr\PhotoBundle\Entity\Photo:
    type: entity
    table: photo
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        path:
            type: string
            lenght: 255
    manyToOne:
        menu:
            targetEntity: Menu
            inversedBy: photos
            joinColumn:
                name: menu_id
                referencedColumnName: id